name: Release

on:
  push:
    tags: ["v*"]
    branches: ["dev"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, darwin-latest]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Setting up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true

      - name: Build
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go env GOOS
#          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o green-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload binaries to release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/${{ matrix.os }}-${{ matrix.arch }}
          tag: ${{ github.ref }}